### ISSUE TITLE
The project is not running 

### ISSUE THREAD

**Issue by aftab0000** [Mozartted/Angular2-Sails-starter-pack#2]
I found that there are two libraries are missing in package.json. I added following two libraries. 

1. extract-text-webpack-plugin
2. webpack-merge 

After adding those libraries when I ran sails lift I got following error message. Any idea?

> ERROR in /Angular2-Sails-starter-pack/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts
> (23,22): error TS2415: Class 'WebSocketSubject<T>' incorrectly extends base class 'AnonymousSubject<T>'.
>   Types of property 'lift' are incompatible.
>     Type '<R>(operator: Operator<T, R>) => WebSocketSubject<R>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<T>'.
>       Type 'WebSocketSubject<R>' is not assignable to type 'Observable<T>'.
>         Types of property 'operator' are incompatible.
>           Type 'Operator<any, R>' is not assignable to type 'Operator<any, T>'.
>             Type 'R' is not assignable to type 'T'.
> 
> ERROR in /Angular2-Sails-starter-pack/node_modules/rxjs/Subject.d.ts
> (16,22): error TS2415: Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
>   Types of property 'lift' are incompatible.
>     Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
>       Type 'Observable<T>' is not assignable to type 'Observable<R>'.
>         Type 'T' is not assignable to type 'R'.
> error: sails-webpack: [ '/Angular2-Sails-starter-pack/node_modules/rxjs/observable/dom/WebSocketSubject.d.ts\n\u001b[37m(\u001b[39m\u001b[36m23\u001b[39m,\u001b[36m22\u001b[39m): \u001b[31merror TS2415: Class \'WebSocketSubject<T>\' incorrectly extends base class \'AnonymousSubject<T>\'.\u001b[39m\n\u001b[31m  Types of property \'lift\' are incompatible.\u001b[39m\n\u001b[31m    Type \'<R>(operator: Operator<T, R>) => WebSocketSubject<R>\' is not assignable to type \'<R>(operator: Operator<T, R>) => Observable<T>\'.\u001b[39m\n\u001b[31m      Type \'WebSocketSubject<R>\' is not assignable to type \'Observable<T>\'.\u001b[39m\n\u001b[31m        Types of property \'operator\' are incompatible.\u001b[39m\n\u001b[31m          Type \'Operator<any, R>\' is not assignable to type \'Operator<any, T>\'.\u001b[39m\n\u001b[31m            Type \'R\' is not assignable to type \'T\'.\u001b[39m',
>   '/Angular2-Sails-starter-pack/node_modules/rxjs/Subject.d.ts\n\u001b[37m(\u001b[39m\u001b[36m16\u001b[39m,\u001b[36m22\u001b[39m): \u001b[31merror TS2415: Class \'Subject<T>\' incorrectly extends base class \'Observable<T>\'.\u001b[39m\n\u001b[31m  Types of property \'lift\' are incompatible.\u001b[39m\n\u001b[31m    Type \'<R>(operator: Operator<T, R>) => Observable<T>\' is not assignable to type \'<R>(operator: Operator<T, R>) => Observable<R>\'.\u001b[39m\n\u001b[31m      Type \'Observable<T>\' is not assignable to type \'Observable<R>\'.\u001b[39m\n\u001b[31m        Type \'T\' is not assignable to type \'R\'.\u001b[39m' ]

**Comment by aftab0000** [comment]
Got the solution. Need to update rxjs version to 5.4.3.

**Comment by Mozartted** [comment]
@aftab0000 Nice...there are several upgrades I need to make on this project... thanks for the update ...
